#!/usr/bin/env bash
# Script changes the user as nginx instead of root

# Kill another server process
pkill -f apache2

# change owner and group of nginx configuration files
chown nginx:nginx /etc/nginx/nginx.conf

# give permission for user of nginx config file
chmod 700 /etc/nginx/nginx.conf

# nginx must be listening on all active IPs on port 8080
sed -i 's/80 defailt_server/8080 default_server/' /etc/nginx/sites-available/default

# restart nginx with the prev config
sudo -u nginx service nginx start
